[env:genericCH32X035F7P6]
platform = ch32v
board = genericCH32X035F7P6
# framework = ch32v003fun  <-- コメントアウト
upload_protocol = wlink

build_flags =
    -Isrc
    -nostartfiles
    -Wl,-T"lib/EVT/EXAM/SRC/Ld/Link.ld"
    -DCH32X035
